In [4]:
import numpy as np

### Транспонирование матрицы

In [10]:
A = np.random.randint(-10,10,(3,4))
print(A)

[[-10  -7   6   1]
 [ -2  -8  -1   4]
 [  5  -2   9   2]]


In [15]:
A_T = A.T
print("Транспонированная матрица\n",A_T)

Транспонированная матрица
 [[-10  -2   5]
 [ -7  -8  -2]
 [  6  -1   9]
 [  1   4   2]]


Свойство 1. Дважды транспонированная матрица равна исходной матрице:

In [16]:
A = np.random.randint(-10,10,(3,4))
print(A)
print((A.T).T)

[[ -2   1  -9  -8]
 [  0 -10   9   8]
 [ -6   9   4   6]]
[[ -2   1  -9  -8]
 [  0 -10   9   8]
 [ -6   9   4   6]]


Свойство 2. Транспонирование суммы матриц равно сумме транспонированных матриц:

In [20]:
A = np.random.randint(-10,10,(3,4))
B = np.random.randint(0,50,(3,4))
L = (A+B).T
R = A.T + B.T
print("Транспонирование суммы:\n",L)
print("Сумма транспонированных матриц:\n",R)

Транспонирование суммы:
 [[29 36  4]
 [28 19  8]
 [16 27 37]
 [48  3 39]]
Сумма транспонированных матриц:
 [[29 36  4]
 [28 19  8]
 [16 27 37]
 [48  3 39]]


Свойство 3. Транспонирование произведения матриц равно произведению транспонированных матриц расставленных в обратном порядке

In [35]:
A = np.random.randint(-10,10,(3,4))
B = np.random.randint(0,20,(4,3))
L = (A.dot(B)).T
R = (B.T).dot(A.T)
print("Транспонирование произведения матриц:\n",L)
print("Произведение транспонированных матриц расставленных в обратном порядке:\n",R)

Транспонирование произведения матриц:
 [[ -79  -58  106]
 [ -94  -72  119]
 [-267 -175  422]]
Произведение транспонированных матриц расставленных в обратном порядке:
 [[ -79  -58  106]
 [ -94  -72  119]
 [-267 -175  422]]


Свойство 4. Транспонирование произведения матрицы на число равно произведению этого числа на транспонированную матрицу:

In [42]:
A = np.random.randint(0,20,(3,4))
k = 5
L = (k * A).T
R = k * A.T
print("Транспонирование произведения матрицы на число:\n",L)
print("Произведение этого числа на транспонированную матрицу:\n",R)

Транспонирование произведения матрицы на число:
 [[20 40 35]
 [10 70 50]
 [80 10  5]
 [75 65 55]]
Произведение этого числа на транспонированную матрицу:
 [[20 40 35]
 [10 70 50]
 [80 10  5]
 [75 65 55]]


*Свойство 5*. Определители исходной и транспонированной матрицы совпадают:

In [46]:
A = np.random.randint(0,5,(3,3))
A_det = np.linalg.det(A)
A_T_det = np.linalg.det(A.T)
print("Определитель исходной матрицы:",format(A_det, '.9g'))
print("Определитель транспонированной матрицы:",format(A_T_det, '.9g'))

Определитель исходной матрицы: 32
Определитель транспонированной матрицы: 32


### Действия над матрицами

#### Умножение матрицы на число

In [56]:
A = np.random.randint(-5,5,(3,3))
print(A)
print("Произведение матрицы на число:\n",A * 4)

[[ 1 -2 -4]
 [ 3 -5  3]
 [-2 -1  0]]
Произведение матрицы на число:
 [[  4  -8 -16]
 [ 12 -20  12]
 [ -8  -4   0]]


Свойство 1. Произведение единицы и любой заданной матрицы равно заданной матрице

In [73]:
A = np.matrix('7 3 5; 4 5 9 ;1 2 1')
print("Матрица умноженная на единицу:\n",A * 1)

Матрица умноженная на единицу:
 [[7 3 5]
 [4 5 9]
 [1 2 1]]


Свойство 2. Произведение нуля и любой матрицы равно нулевой матрице, размерность которой равна исходной матрицы

In [74]:
A = np.matrix('7 3 5; 4 5 9 ;1 2 1')
print("Произведение матрицы на ноль:\n",A * 0)

Произведение матрицы на ноль:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


Свойство 3. Произведение матрицы на сумму чисел равно сумме произведений матрицы на
каждое из этих чисел

In [76]:
A = np.matrix('7 3 5; 4 5 9 ;1 2 1')
q = 5
p = 4
L = (q + p) * A
R = q * A + p * A
print("Произведение матрицы на сумму чисел:\n", L)
print("Сумма произведений матрицы на каждое из этих чисел:\n", R)

Произведение матрицы на сумму чисел:
 [[63 27 45]
 [36 45 81]
 [ 9 18  9]]
Сумма произведений матрицы на каждое из этих чисел:
 [[63 27 45]
 [36 45 81]
 [ 9 18  9]]


Свойство 4. Произведение матрицы на произведение двух чисел равно произведению второго
числа и заданной матрицы, умноженному на первое число:

In [78]:
A = np.matrix('7 3 5; 4 5 9 ;1 2 1')
q = 5
p = 4
L = (q * p) * A
R = q * (p * A)
print("Произведение матрицы на произведение двух чисел:\n", L)
print("Произведение второго числа и заданной матрицы, умноженному на первое число \n", R)

Произведение матрицы на произведение двух чисел:
 [[140  60 100]
 [ 80 100 180]
 [ 20  40  20]]
Произведение второго числа и заданной матрицы, умноженному на первое число 
 [[140  60 100]
 [ 80 100 180]
 [ 20  40  20]]


Свойство 5. Произведение суммы матриц на число равно сумме произведений этих матриц на
заданное число:

In [80]:
A = np.matrix('7 3 5; 4 5 9 ;1 2 1')
B = np.matrix('5 6 1; 10 7 9; 2 4 5')
k = 100
L = k * (A + B)
R = k * A + k * B
print("Произведение суммы матриц на число:\n", L)
print("Сумма произведений этих матриц на заданное число:\n", R)

Произведение суммы матриц на число:
 [[1200  900  600]
 [1400 1200 1800]
 [ 300  600  600]]
Сумма произведений этих матриц на заданное число:
 [[1200  900  600]
 [1400 1200 1800]
 [ 300  600  600]]


#### сложение матрицы

Свойство 1. Коммутативность сложения. От перестановки матриц их сумма не изменяется:

In [81]:
A = np.matrix('7 3 5; 4 5 9 ;1 2 1')
B = np.matrix('5 6 1; 10 7 9; 2 4 5')
L = A + B
R = B + A
print("Сумма А + В:\n", L)
print("Сумма В + А:\n", R)

Сумма А + В:
 [[12  9  6]
 [14 12 18]
 [ 3  6  6]]
Сумма В + А:
 [[12  9  6]
 [14 12 18]
 [ 3  6  6]]


Свойство 2. Ассоциативность сложения.
Результат сложения трех и более матриц не зависит от порядка, в котором эта операция будет выполняться

In [83]:
A = np.matrix('7 3 5; 4 5 9 ;1 2 1')
B = np.matrix('5 6 1; 10 7 9; 2 4 5')
C = np.matrix('1 0 7; 15 9 3; 3 4 -1')
L = A + (B + C)
R = (A + B) + C
print("Сумма A + (B + C):\n", L)
print("Сумма (A + B) + C:\n", R)

Сумма A + (B + C):
 [[13  9 13]
 [29 21 21]
 [ 6 10  5]]
Сумма (A + B) + C:
 [[13  9 13]
 [29 21 21]
 [ 6 10  5]]


Свойство 3. Для любой матрицы существует противоположная ей, такая, что их сумма является нулевой матрицей :

In [87]:
Z = np.matrix('0 0; 0 0')
L = A + (-1)*A
print("сумма исходной и противоположной ей матриц:\n", L)
print("Нулевая матрица:\n",Z)

сумма исходной и противоположной ей матриц:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]
Нулевая матрица:
 [[0 0]
 [0 0]]


#### Умножение матриц

In [89]:
A = np.random.randint(-5,5,(3,3))
B = np.random.randint(-10,5,(3,3))
C = A.dot(B)
print(C)

[[  2  -4 -25]
 [ 22  46  20]
 [ 29  17  26]]


Свойство 1. Ассоциативность умножения. Результат умножения матриц не зависит от порядка, в котором будет выполняться эта операция

In [91]:
A = np.random.randint(-5,5,(3,3))
B = np.random.randint(-10,5,(3,3))
С = np.random.randint(-10,10,(3,3))
L = A.dot(B.dot(C))
R = (A.dot(B)).dot(C)
print("Произведение A * (B * C):\n", L)
print("Произведение (A * B) * C:\n", R)

Произведение A * (B * C):
 [[ 129  -63  596]
 [ 282  336 1137]
 [-154 -202 -888]]
Произведение (A * B) * C:
 [[ 129  -63  596]
 [ 282  336 1137]
 [-154 -202 -888]]


Свойство 2. Дистрибутивность умножения. Произведение матрицы на сумму матриц равно сумме произведений матриц

In [92]:
A = np.random.randint(-5,5,(3,3))
B = np.random.randint(-10,5,(3,3))
С = np.random.randint(-10,10,(3,3))
L = A.dot(B + C)
R = A.dot(B) + A.dot(C)
print("Произведение A * (B + C):\n", L)
print("Произведение A * B + A * C:\n", R)

Произведение A * (B + C):
 [[-126 -195   14]
 [  13   82   -6]
 [  88   55   86]]
Произведение A * B + A * C:
 [[-126 -195   14]
 [  13   82   -6]
 [  88   55   86]]


Свойство 3. Умножение матриц в общем виде не коммутативно. Это означает, что для матриц не выполняется правило независимости произведения от перестановки множителей

In [93]:
A = np.random.randint(-5,5,(3,3))
B = np.random.randint(-10,5,(3,3))
L = A.dot(B)
R = B.dot(A)
print("Произведение A * B:\n", L)
print("Произведение B * A:\n", R)

Произведение A * B:
 [[22 46 19]
 [16 36  9]
 [ 9  1 -3]]
Произведение B * A:
 [[ 41  20   0]
 [-27 -22  31]
 [ 58  20  36]]


Свойство 4. Произведение заданной матрицы на единичную равно исходной матрице

In [97]:
A = np.matrix('5 4; 4 7')
E = np.matrix('1 0; 0 1')
L = E.dot(A)
R = A.dot(E)
print("Произведение заданной матрицы на единичную:\n", L)
print("Произведение единичной матрицы на заданную:\n", R)
print("Исходная матрица:\n", A)

Произведение заданной матрицы на единичную:
 [[5 4]
 [4 7]]
Произведение единичной матрицы на заданную:
 [[5 4]
 [4 7]]
Исходная матрица:
 [[5 4]
 [4 7]]


Свойство 5. Произведение заданной матрицы на нулевую матрицу равно нулевой матрице

In [98]:
A = np.matrix('5 4; 4 7')
Z = np.matrix('0 0; 0 0')
L = Z.dot(A)
R = A.dot(Z)
print("Произведение заданной матрицы на нулевую:\n", L)
print("Произведение нулевой матрицы на заданную:\n", R)
print("Исходная матрица:\n", Z)

Произведение заданной матрицы на нулевую:
 [[0 0]
 [0 0]]
Произведение нулевой матрицы на заданную:
 [[0 0]
 [0 0]]
Исходная матрица:
 [[0 0]
 [0 0]]


### Определитель матрицы

In [107]:
A = np.random.randint(1,5,(3,3))
print(A)

[[4 3 1]
 [1 3 1]
 [2 3 4]]


In [108]:
np.linalg.det(A)

27.0

#### Свойства определителя матрицы.
Свойство 1. Определитель матрицы остается неизменным при ее транспонировании


In [109]:
A = np.random.randint(1,5,(3,3))
print(A)
print(A.T)
det_A = round(np.linalg.det(A), 3)
det_A_t = round(np.linalg.det(A.T), 3)
print("Опеределитель матрицы:",det_A)
print("Определитель транспонированной матрицы:",det_A_t)

[[3 1 3]
 [4 4 1]
 [4 4 2]]
[[3 4 4]
 [1 4 4]
 [3 1 2]]
Опеределитель матрицы: 8.0
Определитель транспонированной матрицы: 8.0


Свойство 2. Если у матрицы есть строка или столбец, состоящие из нулей, то определитель такой матрицы равен нулю

In [112]:
A = np.matrix('0 41 2; 0 5 9; 0 88 21')
print(A)
print("Опеределитель матрицы:", np.linalg.det(A))

[[ 0 41  2]
 [ 0  5  9]
 [ 0 88 21]]
Опеределитель матрицы: 0.0


Свойство 3. При перестановке строк матрицы знак ее определителя меняется на противоположный

In [114]:
A = np.matrix('0 41 2; 10 5 9; 0 88 21')
print(A)
print("Определитель матрицы А:",round(np.linalg.det(A), 3))
B = np.matrix('10 5 9; 0 41 2; 0 88 21')
print(B)
print("Определитель матрицы В:",round(np.linalg.det(B), 3))

[[ 0 41  2]
 [10  5  9]
 [ 0 88 21]]
Определитель матрицы А: -6850.0
[[10  5  9]
 [ 0 41  2]
 [ 0 88 21]]
Определитель матрицы В: 6850.0


Свойство 4. Если у матрицы есть две одинаковые строки, то ее определитель равен нулю

In [116]:
A = np.matrix('0 41 2; 0 41 2; 16 88 21')
print(A)
print("Определитель матрицы А:",np.linalg.det(A))

[[ 0 41  2]
 [ 0 41  2]
 [16 88 21]]
Определитель матрицы А: 0.0


Свойство 5. Если все элементы строки или столбца матрицы умножить на какое-то число, то и определитель будет умножен на это число

In [117]:
A = np.random.randint(1,5,(3,3))
print(A)
k = 10
B = A.copy()
B[2, :] = k * B[2, :]
print(B)
det_A = round(np.linalg.det(A), 3)
det_B = round(np.linalg.det(B), 3)
print("Опеределитель матрицы:",det_A * k)
print("Определитель матрицы умноженной на число:",det_B)

[[2 2 1]
 [4 2 4]
 [1 3 3]]
[[ 2  2  1]
 [ 4  2  4]
 [10 30 30]]
Опеределитель матрицы: -180.0
Определитель матрицы умноженной на число: -180.0


Свойство 6. Если все элементы строки или столбца можно представить как сумму двух слагаемых, то определитель такой матрицы равен сумме определителей двух соответствующих матриц

In [138]:
A = np.matrix('1 2 3; -1 31 4; 4 5 6')
B = np.matrix('1 2 3; 9 8 7; 4 5 6')
C = A.copy()
C[1, :] += B[1, :]
print(C)
print(A)
print(B)
R = round(np.linalg.det(C), 3)
L = round(np.linalg.det(A), 3) + round(np.linalg.det(B), 3)
print("Определитель матрицы C:", R)
print("Определитель суммы двух матриц:", L)

[[ 1  2  3]
 [ 8 39 11]
 [ 4  5  6]]
[[ 1  2  3]
 [-1 31  4]
 [ 4  5  6]]
[[1 2 3]
 [9 8 7]
 [4 5 6]]
Определитель матрицы C: -177.0
Определитель суммы двух матриц: -177.0


Свойство 7. Если к элементам одной строки прибавить элементы другой строки, умноженные на одно и тоже число, то определитель матрицы не изменится

In [140]:
A = np.random.randint(1,5,(3,3))
k = 2
B = A.copy()
B[1, :] = B[1, :] + k * B[0, :]
print(A)
print(B)
R = round(np.linalg.det(A), 3)
L = round(np.linalg.det(B), 3)
print("Определитель матрицы A:", R)
print("Определитель матрицы B:", L)

[[2 2 3]
 [1 3 1]
 [4 4 2]]
[[2 2 3]
 [5 7 7]
 [4 4 2]]
Определитель матрицы A: -16.0
Определитель матрицы B: -16.0


Свойство 8. Если строка или столбец матрицы является линейной комбинацией других строк (столбцов), то определитель такой матрицы равен нулю

In [141]:
A = np.random.randint(1,5,(3,3))
print(A)
k = 2
A[1, :] = A[0, :] + k * A[2, :]
print(A)
K = round(np.linalg.det(A), 3)
print("Определитель матрицы A:", K)

[[1 1 2]
 [3 1 2]
 [4 1 2]]
[[1 1 2]
 [9 3 6]
 [4 1 2]]
Определитель матрицы A: 0.0


Свойство 9. Если матрица содержит пропорциональные строки, то ее определитель равен нулю

In [142]:
A = np.random.randint(1,5,(3,3))
print(A)
k = 2
A[1, :] = k * A[0, :]
print(A)
K = round(np.linalg.det(A), 3)
print("Определитель матрицы A:", K)

[[4 1 3]
 [4 3 1]
 [3 4 1]]
[[4 1 3]
 [8 2 6]
 [3 4 1]]
Определитель матрицы A: 0.0


### Обратная матрица

In [143]:
A = np.random.randint(1,5,(2,2))
A_inv = np.linalg.inv(A)
print(A_inv)

[[-0.33333333  0.44444444]
 [ 0.33333333 -0.11111111]]


Свойство 1. Обратная матрица обратной матрицы есть исходная матрица:

In [145]:
A = np.random.randint(1,5,(2,2))
A_inv = np.linalg.inv(A)
A_inv_inv = np.linalg.inv(A_inv)
print("Определитель исходной матрицы:\n",A)
print("Определитель обратной обратной матрицы A:\n",A_inv_inv)

Определитель исходной матрицы:
 [[3 4]
 [4 4]]
Определитель обратной обратной матрицы A:
 [[3. 4.]
 [4. 4.]]


Свойство 2. Обратная матрица транспонированной матрицы равна транспонированной матрице от обратной матрицы:

In [146]:
A = np.random.randint(1,5,(2,2))
L = np.linalg.inv(A.T)
R = (np.linalg.inv(A)).T
print("Обратная матрица транспонированной матрицы:\n",L)
print("Транспонированная матрица от обратной матрицы:\n", R)

Обратная матрица транспонированной матрицы:
 [[ 0.30769231 -0.23076923]
 [-0.07692308  0.30769231]]
Транспонированная матрица от обратной матрицы:
 [[ 0.30769231 -0.23076923]
 [-0.07692308  0.30769231]]


Свойство 3. Обратная матрица произведения матриц равна произведению обратных матриц:

In [73]:
A = np.random.randint(1,5,(2,2))
B = np.random.randint(1,5,(2,2))
L = np.linalg.inv(A.dot(B))
R = np.linalg.inv(B).dot(np.linalg.inv(A))
print("Обратная матрица произведения матриц:\n",L)
print("Произведение обратных матриц:\n", R)

[[ 0.09454545  0.03272727]
 [-0.03454545  0.00727273]]
[[ 0.09454545  0.03272727]
 [-0.03454545  0.00727273]]
