решения систем линейных уравнений матричным методом и методом Крамера.

### Матричный метод

In [4]:
import numpy as np

решение системы линейных алгебраических уравнений по матричному методу определяется равенством
$$ X = A^{-1} * B $$

В  случае, если det A не равен нулю, у системы имеется только один вариант решения: при помощи метода обратной матрицы. Если det A=0, то систему нельзя решить данным методом.

Создадим и заполним матрицу

In [15]:
A = np.random.randint(-5, 5,(3,3))
B = np.random.randint(-5, 5,(3,1))
print(A)
print(B)

[[ 4 -5  1]
 [-3 -1  0]
 [ 0  4  3]]
[[-1]
 [-4]
 [-3]]


In [16]:
#Найдем определитель
A_det = np.linalg.det(A)

if round(A_det) != 0: 
    #Найдем обратную и присоединенную матрицу
    A_inv = np.linalg.inv(A)
    R = A_inv.dot(B) 
    i = 1
    for elem in R: 
        print(f"x{i} = {elem}") 
        i += 1
else:
    print("определитель равен 0, систему решить нельзя")

x1 = [1.10144928]
x2 = [0.69565217]
x3 = [-1.92753623]


### Метод Крамера

Для решения системы линейных уравнений методом Крамера из коэффициентов при неизвестных составляется главный определитель системы 

Создадим и заполним матрицу

In [27]:
A = np.random.randint(-5, 5,(3,3))
B = np.random.randint(-5, 5,(3,1))
print(A)
print(B)

[[-3 -2  1]
 [ 2 -5 -5]
 [-4  0 -2]]
[[ 1]
 [ 1]
 [-2]]


In [34]:
#Найдем определитель
A_det  = np.linalg.det(A)

if round(A_det) != 0:
    #Найдем дополнительные определители
    d_1 = A.copy() 
    d_1 [:, 0] = B[:, 0] 
    x1 = round(np.linalg.det(d_1), 3) / round(A_det, 3)
    
    d_2 = A.copy()  
    d_2[:, 1] = B[:, 0] 
    x2 = round(np.linalg.det(d_2), 3) / round(A_det, 3) 
    
    d_3 = A.copy() 
    d_3[:, 2] = B[:, 0] 
    x3 = round(np.linalg.det(d_3), 3) / round(A_det, 3) 
   
    print("x1:", x1, "\nx2:", x2, "\nx3:", x3)
else:
    print("Матрица вырожденная, нельзя продолжить")

x1: 0.24489795918367346 
x2: -0.6122448979591837 
x3: 0.5102040816326531
